[build]
builder = "dockerfile"
dockerfilePath = "railway-deploy/Dockerfile"

[deploy]
startCommand = "catalina.sh run"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3